apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gcast-server.fullname" . }}-postgres-data
  labels:
    {{- include "gcast-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
