apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gcast-server.fullname" . }}-postgres-secret
  labels:
    {{- include "gcast-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
