apiVersion: v1
kind: Service
metadata:
  name: {{ include "gcast-server.fullname" . }}-postgres
  labels:
    {{- include "gcast-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    {{- include "gcast-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - port: 5432
      targetPort: 5432
