apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gcast-server.fullname" . }}-secret
  labels:
    {{- include "gcast-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secretKey | quote }}
  DATABASE_URL: {{ include "gcast-server.databaseUrl" . | quote }}
  SMTP_PASSWORD: {{ .Values.smtp.password | quote }}
